# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-30 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansserver',
            name='orgid',
            field=models.CharField(default=1, max_length=24, verbose_name='所属ID'),
            preserve_default=False,
        ),
    ]
