# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-03 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_networkdevice_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='create_at',
        ),
    ]
